#version 460
layout(local_size_x = 512) in;

layout(set = 0, binding = 0) readonly buffer BufferA {
    float a[];
};
layout(set = 0, binding = 1) readonly buffer BufferC {
    float c[];
};
layout(set = 0, binding = 2) writeonly buffer BufferOut {
    float result[];
};

layout(push_constant) uniform PushConstants {
    int b;
} pc;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    // result[idx] = (a[idx] + float(pc.b)) * c[idx];
    result[idx] = float(pc.b);
}
